#!/usr/bin/env python3
"""
Build photo_kb.js — injects gallery photo data as a JS variable
so the chat feature can reference it without an extra HTTP call.
"""
import json, os

BASE = os.path.dirname(os.path.abspath(__file__))
# data/ is one level up from scripts/
DATA = os.path.join(BASE, '..', 'data', 'photos_metadata.json')
OUT  = os.path.join(BASE, '..', 'docs', 'photo_kb.js')

with open(DATA) as f:
    data = json.load(f)

photos = data['photos']

lines = []
for i, p in enumerate(photos):
    t = p.get('ai_tags', {})
    title   = t.get('poetic_title', '') or ''
    species = t.get('species_cn', '') or ''
    latin   = t.get('species_latin', '') or ''
    cat     = t.get('category', '') or ''
    colors  = ', '.join(t.get('primary_colors', []))
    behavior= t.get('behavior', '') or ''
    camera = p.get('camera', '') or p.get('camera_info', {}).get('camera', '?')
    line = (f"#{i+1:02d} | {p['date']} | {camera} "
           f"| f/{p.get('f_number','?')} | ISO{p.get('iso','?')} "
           f"| {species}{' ('+latin+')' if latin else ''} "
           f"| {cat} | [{colors}] | {behavior} | \"{title}\"")
    lines.append(line)

kb_text = '\n'.join(lines)

js = f"""// Auto-generated by build_photo_kb.py — DO NOT EDIT
const PHOTO_KB = `{kb_text}`;
"""

with open(OUT, 'w') as f:
    f.write(js)

print(f"✅  Wrote {len(lines)} photo records → {OUT}")
