#!/usr/bin/env python3
"""
从 photos_metadata.json 生成 web/gallery-data.js
这是首页画廊数据的唯一生成入口 —— 不再手动维护内联 JSON。

用法：
  python data_to_js.py              # 生成 gallery-data.js
  python data_to_js.py --dry-run    # 只打印统计，不写入
"""

import json, os, sys

BASE = os.path.dirname(os.path.abspath(__file__))
METADATA_JSON = os.path.join(BASE, "..", "data", "photos_metadata.json")
OUTPUT_JS = os.path.join(BASE, "..", "docs", "gallery-data.js")


def build(dry_run=False):
    with open(METADATA_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    photos = data["photos"]

    # 移除冗余 web_paths — 文件名规则已知，前端自行推导
    for p in photos:
        p.pop("web_paths", None)

    # 生成紧凑的单行 JSON（与原来 index.html 内联格式一致）
    photos_json = json.dumps(photos, ensure_ascii=False)

    js_content = f"""// Auto-generated by data_to_js.py — DO NOT EDIT
// Source: data/photos_metadata.json
// Generated at: {data.get('generated_at', 'unknown')}
// Photo count: {len(photos)}

const PHOTOS = {photos_json};
"""

    if dry_run:
        print(f"📸 {len(photos)} 张照片")
        print(f"📏 输出大小约 {len(js_content):,} 字符 ({len(js_content.encode('utf-8')) / 1024:.1f} KB)")
        print(f"📁 将写入: {OUTPUT_JS}")
        return

    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"✅ gallery-data.js 已生成 ({len(photos)} 张照片, {len(js_content.encode('utf-8')) / 1024:.1f} KB)")
    print(f"   → {OUTPUT_JS}")


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    build(dry_run=dry_run)
